import { defineConfig } from 'vite';
import { resolve } from 'node:path';
import { writeFileSync, mkdirSync } from 'node:fs';

/**
 * Library build for proctoring.js.
 *
 * Three formats are produced from one entry:
 *  - ESM  -> bundlers (Vite/Webpack/Rollup), tree-shakeable
 *  - CJS  -> Node `require()` and older toolchains
 *  - UMD  -> a plain <script> tag from unpkg/jsDelivr, exposing `window.Proctoring`
 *
 * `@vladmandic/face-api` is intentionally NOT bundled. It is loaded at runtime
 * from a CDN (see src/face/providers.js) so consumers who never enable face
 * detection never pay the ~2MB download.
 */

/** Emits dist/index.d.ts so TypeScript consumers get types without a build step. */
function emitTypes() {
  return {
    name: 'proctoring-emit-types',
    apply: 'build',
    closeBundle() {
      const outDir = resolve(__dirname, 'dist');
      mkdirSync(outDir, { recursive: true });
      writeFileSync(resolve(outDir, 'index.d.ts'), TYPES, 'utf8');
    },
  };
}

export default defineConfig({
  build: {
    target: 'es2020',
    // Consumers may need to support older browsers; keep the output readable
    // and dependency-free rather than aggressively minified.
    minify: 'esbuild',
    sourcemap: true,
    lib: {
      entry: resolve(__dirname, 'src/index.js'),
      name: 'Proctoring',
      formats: ['es', 'cjs', 'umd'],
      fileName: (format) =>
        ({ es: 'proctoring.js', cjs: 'proctoring.cjs', umd: 'proctoring.umd.js' })[format],
    },
    rollupOptions: {
      // Never bundle the optional peer dependency.
      external: ['@vladmandic/face-api', '@tensorflow/tfjs'],
      output: {
        globals: {
          '@vladmandic/face-api': 'faceapi',
          '@tensorflow/tfjs': 'tf',
        },
        exports: 'named',
      },
    },
    emptyOutDir: true,
    reportCompressedSize: true,
  },
  plugins: [emitTypes()],
});

const TYPES = `// Type definitions for proctoring.js
// Generated by the Vite build — edit src/ and rebuild, not this file.

export type LogLevel = 'silent' | 'error' | 'warn' | 'info' | 'debug';

export type Severity = 'info' | 'low' | 'medium' | 'high' | 'critical';

export type ViolationType =
  | 'tab-hidden'
  | 'window-blur'
  | 'right-click'
  | 'shortcut-used'
  | 'camera-disabled'
  | 'camera-muted'
  | 'camera-denied'
  | 'face-not-detected'
  | 'face-multiple'
  | 'face-looking-away'
  | 'audio-too-loud'
  | 'audio-multiple-voices';

export interface Violation<TDetails = Record<string, unknown>> {
  id: string;
  type: ViolationType | string;
  severity: Severity;
  detector: string | null;
  /** Epoch milliseconds. */
  timestamp: number;
  /** Milliseconds since the session started. */
  elapsedMs: number;
  details: TDetails;
  /**
   * Downscaled webcam frame as a data URL. Only present when
   * report.captureScreenshots is enabled and the violation is visual.
   * Never included in the persisted sessionStorage copy.
   */
  screenshot?: string;
}

export interface DetectorState {
  active: boolean;
  status?: string;
  [key: string]: unknown;
}

export interface Report {
  sessionId: string | null;
  metadata: Record<string, unknown>;
  startedAt: string | null;
  endedAt: string | null;
  generatedAt: string;
  durationMs: number;
  total: number;
  droppedCount: number;
  countsByType: Record<string, number>;
  worstSeverity: Severity | null;
  violations: Violation[];
  score: number;
  detectorStates: Record<string, DetectorState>;
  /** Total in-memory screenshot bytes held by the session. */
  screenshotBytes: number;
  /** Frames discarded because the screenshot budget was exhausted. */
  droppedScreenshots: number;
}

export interface TabsOptions {
  enabled?: boolean;
  trackWindowBlur?: boolean;
  minHiddenMs?: number;
  throttleMs?: number;
}

export interface RightClickOptions {
  enabled?: boolean;
  block?: boolean;
  detectPointerDown?: boolean;
  dedupeMs?: number;
  throttleMs?: number;
  captureTarget?: boolean;
}

export interface ShortcutsOptions {
  enabled?: boolean;
  /**
   * Combos to watch, e.g. ['ctrl+shift+i', 'ctrl+p']. null uses the platform's
   * developer-tools list. Modifiers: ctrl, shift, alt, meta, and mod (meta on
   * macOS, ctrl elsewhere).
   */
  combos?: string[] | null;
  block?: boolean;
}

export interface CameraOptions {
  enabled?: boolean;
  videoElement?: string | HTMLVideoElement | null;
  width?: number;
  height?: number;
  facingMode?: string;
  detectMuted?: boolean;
  detectEnded?: boolean;
  checkIntervalMs?: number;
  throttleMs?: number;
}

export interface FaceOptions {
  enabled?: boolean;
  videoElement?: string | HTMLVideoElement | null;
  provider?: 'cdn' | 'module' | 'custom';
  providerOptions?: {
    scriptUrl?: string;
    modelUrl?: string;
    specifier?: string;
    api?: unknown;
  };
  intervalMs?: number;
  minConfidence?: number;
  requireFace?: boolean;
  awayGraceMs?: number;
  maxFaces?: number;
  lookAwayTolerance?: number;
  throttleMs?: number;
}

export interface AudioOptions {
  enabled?: boolean;
  rmsThreshold?: number;
  loudGraceMs?: number;
  voiceThreshold?: number;
  fftSize?: number;
  smoothingTimeConstant?: number;
  detectMultipleVoices?: boolean;
  throttleMs?: number;
}

export interface BackendOptions {
  enabled?: boolean;
  endpoint?: string | null;
  method?: 'POST' | 'PUT' | 'PATCH';
  headers?: Record<string, string>;
  batchIntervalMs?: number;
  offlineQueue?: boolean;
  includeReport?: boolean;
  retries?: number;
  retryDelayMs?: number;
  timeoutMs?: number;
  minSeverity?: Severity | null;
}

export interface ReportOptions {
  persist?: boolean;
  storageKey?: string;
  maxViolations?: number;
  captureScreenshots?: boolean;
  screenshotMaxWidth?: number;
  screenshotQuality?: number;
  screenshotTypes?: string[] | null;
  screenshotBudgetBytes?: number;
}

export interface ProctorOptions {
  sessionId?: string | null;
  metadata?: Record<string, unknown>;
  tabs?: TabsOptions;
  rightClick?: RightClickOptions;
  shortcuts?: ShortcutsOptions;
  camera?: CameraOptions;
  face?: FaceOptions;
  audio?: AudioOptions;
  backend?: BackendOptions;
  report?: ReportOptions;
  logLevel?: LogLevel;
  severity?: Partial<Record<ViolationType, Severity>>;
}

export interface ProctorEvents {
  ready: unknown;
  started: { startedAt: string; detectors: string[] };
  violation: Violation;
  'detector:ready': { detector: string };
  'detector:error': { detector: string; error: Error };
  'detector:enabled': { detector: string };
  'detector:disabled': { detector: string };
  log: { level: LogLevel; message: string; meta?: unknown };
  stopped: { report: Report };
  error: Error;
}

export declare class Proctor {
  constructor(options?: ProctorOptions);

  options: ProctorOptions;
  started: boolean;

  on<K extends keyof ProctorEvents>(event: K, handler: (payload: ProctorEvents[K]) => void): () => void;
  on(event: string, handler: (payload: unknown) => void): () => void;

  start(overrides?: ProctorOptions): Promise<this>;
  stop(): Report;
  destroy(): void;

  getReport(): Report;
  getViolations(minSeverity?: Severity | null): Violation[];
  hasViolation(type: ViolationType | string): boolean;

  getDetector(name: string): unknown;
  getDetectorState(name: string): DetectorState | null;
  enableDetector(name: string): Promise<boolean>;
  disableDetector(name: string): boolean;
  clearViolations(): void;

  reportViolation(
    type: ViolationType | string,
    details?: Record<string, unknown>,
    meta?: { detector?: string; severity?: Severity; timestamp?: number }
  ): Violation | null;
}

export declare function createProctor(options?: ProctorOptions): Proctor;

export declare const EVENTS: Readonly<Record<string, string>>;
export declare const VIOLATION_TYPES: Readonly<Record<string, ViolationType>>;
export declare const SEVERITY: Readonly<Record<string, Severity>>;
export declare const DEFAULT_OPTIONS: ProctorOptions;
export declare const DEFAULT_SEVERITY: Readonly<Record<string, Severity>>;
export declare const DETECTOR_NAMES: readonly string[];
export declare const DEVTOOLS_COMBOS: Readonly<{ mac: readonly string[]; other: readonly string[] }>;

/** Parse a combo such as 'ctrl+shift+i'. Returns null when it cannot be one. */
export declare function parseCombo(
  raw: string,
  platform?: 'mac' | 'other'
): { ctrl: boolean; shift: boolean; alt: boolean; meta: boolean; key: string; raw: string } | null;

export declare function detectPlatform(): 'mac' | 'other';
export declare const FACE_API_VERSION: string;
export declare const CDN_DEFAULTS: Readonly<{ scriptUrl: string; modelUrl: string }>;
export declare const version: string;

export declare function formatReport(report: Report): string;
export declare function reportToCsv(report: Report): string;
export declare function downloadReport(report: Report, filename?: string): void;
export declare function downloadReportCsv(report: Report, filename?: string): void;
export declare function mergeReports(reports: Report[]): Report;
export declare function diffReports(before: Report, after: Report): { added: Violation[]; addedCount: number; beforeTotal: number; afterTotal: number };
export declare function worstSeverityOf(violations: Violation[]): Severity | 'none';
export declare function formatDuration(ms: number): string;
export declare function computeRms(buffer: Float32Array): number;
export declare function computeSpectralDensity(freqData: Uint8Array, floor?: number): number;

export interface ScreenshotOptions {
  maxWidth?: number;
  quality?: number;
  type?: string;
}

/** Capture the current frame of a video element as a data URL, or null. */
export declare function captureFrame(
  video: HTMLVideoElement | null,
  options?: ScreenshotOptions
): string | null;
export declare function isVisualViolation(
  violationType: string,
  detector: string | null,
  allowedTypes?: string[] | null
): boolean;
export declare function dataUrlBytes(dataUrl: string): number;
export declare const SCREENSHOT_DEFAULTS: Readonly<{ maxWidth: number; quality: number; type: string }>;

export default Proctor;
`;
